### ISSUE TITLE
Missing cog.yaml and predict.py

### ISSUE THREAD

**Issue by zeke** [afiaka87/pyglide#2]
Hey @afiaka87!

I just noticed you [published this model on Replicate](https://replicate.com/afiaka87/pyglide). So cool! 🦆🚗 

I wanted to check out your implementation here on GitHub, but noticed that the `cog.yaml` and `predict.py` files are missing. Are you planning to add those to repo? Let me know if I can help out.

**Comment by afiaka87** [comment]
@zeke Yes thanks for asking, I'll be updating this repo with it yes! Should be done tonight.

**Comment by afiaka87** [comment]
@zeke I've uploaded https://github.com/afiaka87/pyglide-replicate as the code is a bit branched from this one.

**Comment by zeke** [comment]
Niiiice! 🙌🏼 

I see you added a link to the other repo in the README too. :)

Feel free to close this.
